### ISSUE TITLE
doesn't work on catalina

### ISSUE THREAD

**Issue by drselump14** [mandrigin/AlfredSwitchWindows#24]
After I upgraded the OS to catalina, it doesn't work.

It says

```
“EnumWindows” can’t be opened because Apple cannot check it for malicious software.
```

Any help would be appreciated

**Comment by mandrigin** [comment]
@drselump14 I know that there are a couple of issues with this plugin on Catalina. Unfortunately, I can’t upgrade to it myself, because it will break some of the software I need for my job.

What you can try doing:
- go to Alfred preferences
- right-click on the workflow, “Open in Finder”
- there, right-click on EnumWindows and press “open”, confirm it
- open “Security and Privacy” and add EnumWindows there in the Accessibility category

**Comment by drselump14** [comment]
Thanks. It works
