### ISSUE TITLE
'w' doesn't work anymore in Catalina MacOS 10.15

### ISSUE THREAD

**Issue by gbstan** [mandrigin/AlfredSwitchWindows#25]
It seems that on Catalina the alfred command 'w' doesn't allow to switch to windows of any other programme than Safari, i.e. calling 'w' only shows Safari windows but no other window.

This is one of my most used workflows and it would really be fantastic if this could be solved on Catalina.

**Comment by gbstan** [comment]
Launching the core EnumWindows program in the terminal from the workflow folder gives the following:
./EnumWindows --search="Finder"
<items></items>
i.e. other programmes don't return anything for some reason on Catalina

**Comment by gbstan** [comment]
I have checked and Alfred is added to Accessibility settings too.

**Comment by mandrigin** [comment]
@gbstan thanks for your investigation! Unfortunately, I don’t have Catalina right now (can’t install it because it will break some of the software I use for work). I might have access to it early next year and I will try to debug the stuff. 

What if you try to add the EnumWindows itself to the accessibility settings?

**Comment by gbstan** [comment]
Hi @mandrigin: That's a good suggestion. I have tried it but unfortunately it didn't work. Same output in the debugger as well, i.e. only the safari tabs but no other window from any other programme.

**Comment by zihaojiang** [comment]
I have the same problem. Catalina MacOS 10.15

**Comment by ferry-ferry-ferry** [comment]
experiencing the same issue on 10.15.3 (19D76)

**Comment by gbstan** [comment]
Hi @mandrigin, is there a way I can help? This is one of my most used workflows and I would love to have it working again on Catalina.

**Comment by mandrigin** [comment]
@gbstan hey! I’ve recently upgraded myself and facing the same issue. Right now I’m traveling too much to give it enough attention, but I’ll try to debug it asap (maybe in a week or two).

**Comment by gbstan** [comment]
Amazing!

**Comment by fow5040** [comment]
Hi guys - recently started using this Workflow (solid work, btw!) and non-tab window switching doesn't work for me!

Digging a little closer, it seems like `'kCGWindowName'` always returns 'nil' on Catalina 10.15.3 - googling finds other devs running into the same issue. The code that accesses this property is in `EnumWindows/Windows.swift`. 

I've only been playing with this for a while, but it looks like we could either:
-  Reference `'kCGWindowOwnerName'` instead of `'kCGWindowName'` for the Process name
-  Haven't tested yet, but perhaps there are other ways to explicitly access the window name [[similar issue]](https://github.com/koekeishiya/yabai/issues/22#issuecomment-500856621) 

I've been able to get the app half working by referencing `wi.appName` instead of `wi.name`, but then the Alfred result title isn't as appealing any more.

**Comment by mandrigin** [comment]
@fow5040 great findings! can you show the code? (feel free to open a PR here)

**Comment by fow5040** [comment]
Yep - let me fork really quick

**Comment by fow5040** [comment]
Submitted!

**Comment by mandrigin** [comment]
let me take a look

**Comment by mandrigin** [comment]
looks good, let me test it quickly and release

**Comment by mandrigin** [comment]
@fow5040 https://github.com/mandrigin/AlfredSwitchWindows/releases/tag/0.3.2

**Comment by mandrigin** [comment]
Thanks a lot for your help!

**Comment by fow5040** [comment]
Happy to help!

**Comment by gbstan** [comment]
I have just installed the latest version (0.3.3) but it still doesn't seem to work.
I have allowed the EnumWindow to work (via the Security & Privacy -> General when it appeared there) too.

Am I missing something?

**Comment by gbstan** [comment]
It works by typing the name of the app. Then I see a list of all the windows for this app. Unfortunately, the name of each window/tab is the same for all items of this list making it impossible to know which one corresponds to what (contrary to what was possible before when you could literally just search for strings in the titles of the windows/tabs)

**Comment by mandrigin** [comment]
@gbstan I think I found a way to fix it better.

**Comment by gbstan** [comment]
Thank you! Let me know if I can help with testing.

**Comment by mandrigin** [comment]
@gbstan https://github.com/mandrigin/AlfredSwitchWindows/releases/tag/0.3.4

note that Alfred should be allowed to record screen (Catalina will ask on the first 'w')

**Comment by mandrigin** [comment]
updated the readme too

**Comment by mandrigin** [comment]
work for me on 10.15.3

**Comment by ubuntudroid** [comment]
@mandrigin Looks like the latest release does not contain a workflow asset. Is it built and added asynchronously?

**Comment by mandrigin** [comment]
@ubuntudroid whoops, it didn't upload the first time. fixed now, thanks!

**Comment by gbstan** [comment]
Yes, it is working now.
Thank you!
